org.gradle.jvmargs=-Xmx1536m -Xms256m -Dkotlin.daemon.jvm.options=-Xmx512m
org.gradle.daemon=false
android.useAndroidX=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
